import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bjCree = localFont({
  variable: "--font-bj-cree",
  display: "swap",
  src: [
    { path: "./fonts/BJCree/BJCree-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/BJCree/BJCree-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/BJCree/BJCree-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/BJCree/BJCree-Bold.ttf", weight: "700", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bjCree.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
